### ISSUE TITLE
this not issue 

### ISSUE THREAD

**Issue by pretech86** [BigO-Moha/Telegram-DropperRat#1]
thanks for the tool , kindly how can i contact you mr bigo because i familiar with dart and i want to start writing malware by dart but i can't find any resources 

can you help me please

**Comment by BigO-Moha** [comment]
> thanks for the tool , kindly how can i contact you mr bigo because i familiar with dart and i want to start writing malware by dart but i can't find any resources 
> 
> can you help me please 

"https://dart.dev/guides" (documentation) is best resource bro stuck with it.
